# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-07 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190307_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='childtypenames',
            field=models.CharField(max_length=255),
        ),
    ]
